-- MySQL Script generated by MySQL Workbench
-- Tue Jun 21 19:15:28 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema banco_inbanker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco_inbanker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco_inbanker` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `banco_inbanker` ;

-- -----------------------------------------------------
-- Table `banco_inbanker`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_inbanker`.`usuarios` (
  `usu_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `usu_id_face` BIGINT(20) NULL COMMENT '',
  `usu_nome` VARCHAR(45) NULL COMMENT '',
  `usu_imagem` VARCHAR(200) NULL COMMENT '',
  `usu_token_gcm` VARCHAR(200) NULL COMMENT '',
  `data` DATETIME NULL COMMENT '',
  PRIMARY KEY (`usu_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_inbanker`.`transacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_inbanker`.`transacoes` (
  `trans_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `trans_id_user1` BIGINT(20) NULL COMMENT '',
  `trans_nome_user1` VARCHAR(45) NULL COMMENT '',
  `trans_id_user2` BIGINT(20) NULL COMMENT '',
  `trans_nome_user2` VARCHAR(45) NULL COMMENT '',
  `trans_valor` VARCHAR(45) NULL COMMENT '',
  `trans_vencimento` VARCHAR(45) NULL COMMENT '',
  `trans_data` DATETIME NULL COMMENT '',
  `trans_dias` INT NULL COMMENT '',
  `trans_dia_pago` DATETIME NULL COMMENT '',
  `trans_resposta_pedido` TINYINT(3) NULL COMMENT '',
  `trans_resposta_pagamento` TINYINT(3) NULL COMMENT '',
  PRIMARY KEY (`trans_id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
